# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xV5bpqY5ySZRHxaF4c02chnyxftQnQ9k
"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation

model = Model(inputs = inputs, outputs = outputs)

import numpy as np
x = np.random.rand(1000,10)

y = (x.sum(axis=1)>5).astype(int)

model.add(Dense(16, activation = 'relu', input_shape=(10,)))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

model.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy',
    metrics = ['accuracy']
)

model.fit(x,y, epochs = 10, batch_size=32)

test = np.random.rand(1,10)
print(model.predict(test))

